### ISSUE TITLE
Minimal floating window created by minimize command

### ISSUE THREAD

**Issue by jabcreations** [rafcolson/ClearStandbyMemoryScheduler#3] opened 2024-12-22 16:38 UTC
Greetings Raf,

First, thank you for actually working to fix the two problems I reported.

Everything is almost working perfectly with one minor exception. I was looking at my browser's status text and saw a close button. It turns out that the minimize-to-tray function creates a not-hidden window at the bottom-left just above my start button. I can interact with it, restore the window, etc just fine. I've moved it to a less intrusive position for now. Could you please make the window completely disappear when minimized to tray? I've already added the original program to a client's computer and plan to write a blog entry on the Fixed Firefox website that I maintain. I'd love to post about the program bug-free as pretty much everyone needs this if they're running Windows.

**Comment by rafcolson** [comment] 2024-12-22 20:06
Hi @jabcreations. I couldn't reproduce on Windows 11 Home. A screenshot could help me figure out what could be causing this weird behavior on your end. Thanks.

**Comment by jabcreations** [comment] 2024-12-22 20:19
I'm using Windows 10 x64 22H2. I exited and restarted the program to show you the default position it appears at. I use my 4K screen at 2560x1440 so a different resolution might change where this floating window appears.

![3-screenshot](https://github.com/user-attachments/assets/ba27a5e9-062f-4348-8c34-27764a9af91a)

You can get a copy of Windows 10 22H2 here:

https://www.microsoft.com/en-us/software-download/windows10

I was going to recommend downloading the VMware Workstation Player virtualization software however Broadcom killed that off and I recommend staying away from all things Oracle so unfortunately I don't have a proper and thoughtful recommendation for a virtualization software.  🙄︀

**Comment by rafcolson** [comment] 2024-12-23 08:35
I could not reproduce with Windows 10 22H2, however I'm not able to set to a 4K resolution on my old laptop. Nevertheless, if the issue only occurs on startup, it might just be that I omitted a line in the code, which hides the window when _Hide to system tray_ enabled.

I restored that line, so I'm curious whether the problem is solved. I've updated the latest release.

PS: Do you use a Windows XP theme on Windows 10?

**Comment by jabcreations** [comment] 2024-12-23 14:50
I'm at 1440p not 2160p.

I installed the new version and it didn't change. So I uninstalled it and attempted to reinstall it but I got a different error that I reported.

**Comment by rafcolson** [comment] 2024-12-23 16:05
So, to be clear. With all three options enabled, the minimized window will appear also after restarting Windows?

**Comment by jabcreations** [comment] 2024-12-23 18:01
I can no longer confirm due the old version not being uninstalled when the new version installed. If you can fix that with a new version (that removes both 1.0.0.0 and 1.0.0.1) I'll be happy to confirm.

**Comment by jabcreations** [comment] 2024-12-23 18:09
Okay, I manually deleted everything in the following directory:

C:\Users\John\AppData\Local\Apps\2.0

Then installed the newest installer you pushed this morning. All three options are enabled and that minimized window appears right above my start button.

**Comment by rafcolson** [comment] 2024-12-23 18:10
What happens when you restart Windows? Does a minimized window now also appear?

**Comment by rafcolson** [comment] 2024-12-23 18:19
> Okay, I manually deleted everything in the following directory

Uninstalling with _Add/Remove Programs_ didn't work?

**Comment by jabcreations** [comment] 2024-12-23 18:27
Correct, there were some missing files for the 1.0.0.1 release though there was still a confirm file (I think?) and a sub-directory.

**Comment by jabcreations** [comment] 2024-12-23 18:28
> What happens when you restart Windows? Does a minimized window now also appear?

We're developers, we don't speak of such things. 🤫

But I haven't gotten any file-lock problems if that is what you're referring to?

Let me restart and report back...

**Comment by jabcreations** [comment] 2024-12-23 18:32
Okay, I restarted and it came back up but all of the checkboxes were unchecked. I checked them and then clicked the close button to minimize to tray and the minimize floating window still appeared above my start button.

**Comment by rafcolson** [comment] 2024-12-23 18:34
I still don't know with all three options enabled, the minimized window will also appear after restarting Windows.

**Comment by jabcreations** [comment] 2024-12-23 18:51
Does this help?
https://stackoverflow.com/questions/43895376/minimize-function-is-still-showing-bar

I found it via this search:
https://www.google.com/search?sca_esv=706a3250d026367c&udm=2&q=.net+hide+still+shows+minimized+window&spell=1&sa=X&ved=2ahUKEwiI6-HUx76KAxVnRDABHUylAhQQBSgAegQIBxAB&biw=1963&bih=978&dpr=1.3#vhid=lRtvsZJhZr0PdM&vssid=mosaic

**Comment by jabcreations** [comment] 2024-12-23 18:53
This also looks on target though keep in mind I'm a web developer who deals with interpreted code, not compiled code:

https://stackoverflow.com/questions/17681686/minimized-application-showing-above-the-task-bar

**Comment by rafcolson** [comment] 2024-12-23 18:58
Could you try the latest release, please? If that didn't change anything, I will not be able to fix it for the next 4 or 5 weeks.

PS: It's a pity that I can't reproduce the issue on my Windows 10 system. Thanks for your help.

**Comment by jabcreations** [comment] 2024-12-23 19:14
Okay, so I downloaded and installed the new build. It installed cleanly AFAIK offhand. I tried to close to try and it still shows that minimized window.

For now I'm using a clearly very old Taskbar Hide (https://www.eusing.com/hidewindows/bosskey.htm) which technically removes the minimized window and I can see that the program is still technically running in the background for now though it creates blank "icons" so I have to use a shortcut like the one on the desktop to get back to the program. So this will have to do for now I suppose. I really appreciate you just relentlessly attacking the issues. I hope whatever you're doing for 5-6 weeks that you find success and I'll be happy to hear back from you when you return.

**Comment by rafcolson** [comment] 2024-12-23 19:24
Well, I will be very busy studying. I probably will be able to fix the issue, but it will take some time investigating the solution. Thanks for your patience. I'm sorry I couldn't fix all of the issues this weekend.

**Comment by jabcreations** [comment] 2024-12-23 19:40
I'm the developer of an entire web platform built entirely from scratch by myself - I know what it's like to not get everything working properly even after the second or third attempt. But we eventually come back and conquer the task. Good luck with your studies! I look forward to your return.

**Comment by rafcolson** [comment] 2024-12-24 20:45
@jabcreations I couldn't help but give it one other try. So let me know if this change works. Thanks.

**Comment by jabcreations** [comment] 2024-12-24 21:19
I really appreciate the effort though the installer doesn't install the latest version:
![installer](https://github.com/user-attachments/assets/454f3bfb-83ad-4657-95a6-b12533596d1c)

I extract the ZIP contents and overwrite whatever the last version I downloaded. Even deleting the extracted folder AND the installed copy when I installed 1.0.0.3 from scratch I went to the Task Manager, right-clicked on the  process in the Details tab, went to the file location, got the properties window, went to that Details tab and it says version 1.0.0.0.

So I did more searching because I'm good at it via persistence. I found a couple threads:

This one is small though seems very on-topic:
https://stackoverflow.com/questions/17641162/minimizing-a-system-windows-form-in-tray-in-c-sharp-without-seeing-it-hanging-wh

This one is the kind that Google buries because clearly screw us:
https://stackoverflow.com/questions/1730731/how-to-start-winform-app-minimized-to-tray

That second URL has a lot of details and looks very on-topic. But I can't test it if the installer gives me 1.0.0.0 instead of 1.0.0.3.

**Comment by rafcolson** [comment] 2024-12-24 21:37
It was actually v1.0.0.3 but forgot about updating the info (see date in info). I've drafted yet another release. Let me know whether the minimized window is gone now.

> This one is small though seems very on-topic

The solution proposed here, is not solid, or so it seems. Hiding the application with `Hide()`, doesn't seem to work after it is minimized with `WindowState = FormWindowState.Minimized`. And so it would be necessary to hide it, just before it is minimized. Rather inconvenient.

https://stackoverflow.com/questions/1052913/how-to-detect-when-a-windows-form-is-being-minimized

**Comment by jabcreations** [comment] 2024-12-25 01:07
Raf, thanks. I just got back in. I deleted everything (install files and the previous installation), extracted, installed, tested and the same thing. It's 1.0.0.4 though it still shows the minimized floating window. Thank you for trying!

I don't know the syntax the lingo associated with very-Microsoft languages. Is there another project that uses the same languages/frameworks/etc that you could inquire in to? I use Winamp, Tixati and Volume2 for example.

**Comment by rafcolson** [comment] 2024-12-25 01:32
> Thank you for trying!

It's unfortunate. Thank you for testing.

Using v1.0.0.0 with all three options enabled, probably works best for you, once the system is restarted. I suppose it then will only be visible in the tray.

> Is there another project that uses the same languages/frameworks/etc that you could inquire in to? I use Winamp, Tixati and Volume2 for example.

I'm not sure what you mean.

**Comment by jabcreations** [comment] 2024-12-25 02:13
I'm not big in to Git and I even scrapped the few things I had one here after Microsoft waltzed in and overthrew the place. Though I still interact with other developers on here from time to time. I mentioned Winamp, Tixati and Volume2 as examples that might have projects on here that you could speak with other developers about resolving the problem. I would have mentioned JDownloader but it's Java and their window management is pretty bad. But I've got Winamp, Tixati and Volume2 minimizing to the tray without any incident. Unfortunately Microsoft languages aren't my thing so I can only kind-of help with what I hope to be helpful recommendations and some basic research. I've got quite the stack of code related issues I'm trying to work through the next two weeks myself. My best piece of advice: just keep attacking the tasks. That is how I got so good at what I do. Plus ignore idiots who scream to play it safe like when I disabled the page file and found out how much better the performance was (and that eventually, ~20 years later, led me here). I'll still be here to help test things out. You definitely have the vision and know what needs to be done. If you keep working on the execution you will get there. Plus when I figure stuff out that wasn't properly clarified I usually blog about it so other developers don't have to go through the same BS I did. Any way, hopefully starting tomorrow I'll have two solid weeks of non-interrupted days to really finish cleaning up some really obstinate tasks standing between where I'm trying to go and me. I'll be here to test any more changes. Thank you for tenacity to keep trying.

**Comment by rafcolson** [comment] 2024-12-28 08:04
@jabcreations Hi. Gave it yet another try. Should be fixed, but you never know. Checkout latest release.

**Comment by jabcreations** [comment] 2024-12-29 02:28
Raf, awesome, thank you! I shot a very short video to show you what it does now:

To prevent search engines from trying to index it just take the two parts of the URL and put them together:
jabcreations.com
and
/files/v/ClearStandbyMemoryScheduler _2024.12.28-21.22.mp4

So yes, it does very briefly "flash" at the same bottom-left part of the screen just above my start button but it _does_ properly disappear now! **_Thank you!_**

I'm curious, what do you think that you changed that did the trick? Also, is it possible to hide the window and then minimize it? Absolutely purely optional of course, it's just pure curiosity. 🙂︀

**Comment by rafcolson** [comment] 2024-12-29 06:15
> So yes, it does very briefly "flash" at the same bottom-left part of the screen just above my start button but it _does_ properly disappear now! **_Thank you!_**

I noticed it in the video. Not sure anything can be done about it. It won't flash on my pc's though.

> I'm curious, what do you think that you changed that did the trick?

It works by hiding the window just after it is minimized (closing will minimize with _Hide to system tray_ enabled). I'm not sure whether upgrading to the latest .NET framework has changed anything, but I think this didn't work with 4.72. I could tackle it with debugging the visibility property of the window.

> Also, is it possible to hide the window and then minimize it? Absolutely purely optional of course, it's just pure curiosity. 🙂︀

I could look into it further.

**Closed as completed** 2024-12-29 06:19 UTC

**Comment by rafcolson** [comment] 2024-12-30 02:22
@jabcreations There's a new release, which may fix the flashing issue or not. If you like to discuss the issue further, please continue in #5.

Note that this release uses a different installer. This also means that any version up to _v1.0.0.6_ should be uninstalled manually. With this change there should be no more issues with installing newer versions (#6).

**Comment by jabcreations** [comment] 2024-12-30 03:25
NICE! Great job Raf! The flashing is gone (slight chance I could have survived) and I like the new installer! I'm not a big fan of the Program Files dump folder. Now the program is, for what it does, is as perfect as I can imagine it to be.

I'm getting behind on my work though I plan on blogging about your software in the next few weeks (added to my calendar). Literally everyone who is running Windows needs to purge the intentional waste by Microsoft of memory.

Thank you very much for your efforts!

**Comment by rafcolson** [comment] 2025-01-07 05:16
> I'm getting behind on my work though I plan on blogging about your software in the next few weeks (added to my calendar). Literally everyone who is running Windows needs to purge the intentional waste by Microsoft of memory.

@jabcreations
Just to give you a heads up, I've made some additional changes to the application. Now there's the option to set a condition (view [READ.ME](https://github.com/rafcolson/ClearStandbyMemoryScheduler?tab=readme-ov-file#clearstandbymemoryscheduler)) and I've added support for High DPI. You may have noticed that previously the resolution was fixed, but now everything stays crisp when adjusting Windows _Scale_ settings.

**Comment by jabcreations** [comment] 2025-01-07 06:51
>If the threshold is set to Available memory

I'm guessing that translates to "if this is set great than 0"?

I'm very limited on time though I want to give you some helpful feedback. Frankly, by default, I hate it. I don't know what it does. My best guess is that it leaves some of the standby memory alone (e.g. 5000MB leaves 5GB or less standby alone)? But then that defeats the whole purpose of the program! The only point of standby memory is to literally waste RAM by Microsoft to help RAM vendors sell more RAM. It shouldn't exist for any reason to begin with.

...or does it attempt to reduce RAM to only that amount? What if I have 20GBs of tabs open?

So I can't say I comprehend what the point is. Before you make any more changes please clarify what the effective intention is. Then I'll help you reword it and then tell you what I think sans all of the guess-work.

**Comment by rafcolson** [comment] 2025-01-07 08:49
> (...) Frankly, by default, I hate it. I don't know what it does. (...)

If you don't know what it does, there's no valid basis for hating it, is there?

I'm sorry you didn't understand but I don't know how to be any clearer. Understanding what _standby_ memory is and where it can be monitored (in Windows Task Manager), would imply there's an awareness of the concept of _available_ memory. This is the actual free memory.

And so, the amount specified defines the threshold, to optimize functionality. For example, on PCs with 16GB of RAM clearing _standby_ memory would only be beneficial with running large programs. The setting _Available memory_ will then be useful to determine the minimum amount of _available_ memory you want be keep free from _standby_ memory. The setting _Standby memory_ is just another approach to limit execution.

Why limit? At a certain point Windows will not be gathering _standby_ data as much. When _standby_ memory is "full", sort of speak, the system doesn't have to process as much anymore to serve that end. And so, if there's still enough _available_ memory for the system to work properly, it's better to leave it as is. But if you would clear _standby_ memory regardless, it will take more processing power, again and again.

If you don't like it or have a system with 4-8GB of RAM, set to _No threshold_, leveraging a small amount of processing power.

**Comment by jabcreations** [comment] 2025-01-07 10:18
Okay, I think I now comprehend what the new option is. If you have 16GB, are actually using 12GB and 4GB is being wasted by standby then setting this to 2000MB would result in the program clearing 2,000MB of standby memory.

If my interpretation is correct then, I still hate it. lol sorry but I just hate the whole concept of standby memory with a burning passion, it's got nothing to do with you.

So basically two things:

1. I do see what I think your intentions are. When I first realized that Windows was intentionally wasting RAM was when I was browsing the "File Summary" of the program [RAMMap](https://learn.microsoft.com/en-us/sysinternals/downloads/rammap). There I could see 1GB of space being wasted by a video I had watched an entire week earlier! A week! I used the "Empty" file menu to clear out all of the "cache" intentionally wasting my memory away. Of course this quickly got very tedious since Microsoft programmed anything and everything it could to waste RAM. Any way, in those earlier days because my RAM was being maxed out by this "feature" it would sometimes freeze up my computer or make it "stumble" a bit. So I get the notion of this new feature in regards to preventing that from occurring.

2. I still think the last version is as close to perfection as I'd expect anyone to get to. That being said the renewed conversation reminded me of some scenarios where one minute is not a sufficiently short enough span of time to execute clearing the standby memory.

I don't get to play games much though when I do I obviously have to download them. I've noticed that anything downloaded goes straight in to standby automatically and that very quickly grows the standby waste of memory.

Even worse: large file transfers between two drives, especially SSDs and mot especially NVMe SSDs. I actually had to create a batch program to clear standby once every, I think five seconds. If I recall correctly some programs were crashing because I disabled the useless page file feature from the 1980s. There is a massive difference between not having enough memory because it costs over $1,000 for 16KB of RAM and manufacturers trying to blindly compete on price by putting 8GB or even 4GB of RAM in to low end laptops. I myself only have 32GB as I got screwed on the timing of my last computer build. I should have 64GB though they were all sold out one week before Christmas a few years ago.

So I would explain the options a bit differently.

For those who have a burning passion for wasting RAM by standby:

No threshold: always clear the entire standby memory regardless of how much space it may using. This could potentially hurt computer performance on older system during times where standby memory usage is intense such as large and faster downloads or large SSD-to-SSD drive transfers.

I'm not sure about the others but that definition for no threshold makes the most sense. I've got an AMD 3800 with 32GB of RAM and it's been years since clearing standby memory hurt performance even for the briefest of moments as far as I can recall. Okay, I got to get back to work. I hope this feedback is useful. I ultimately do this feature option comes from a good place. I think correlating it better to the activities and scenarios would make it make more sense to people who would choose to set one option over another would make it much easier to comprehend. I wouldn't change it except maybe ask or analyze and optimize for the computer. Before making any effort on that I'd be happy to go back-and-forth on the real-world use for each option. Then I think I might be able to help you optimize detecting the default settings and any other changes in the program itself to save you time on implementation once you've got the conceptual work ironed out. I think you do, it just needs to be better clarified.

**Comment by rafcolson** [comment] 2025-01-07 10:57
> Okay, I think I now comprehend what the new option is. If you have 16GB, are actually using 12GB and 4GB is being wasted by standby then setting this to 2000MB would result in the program clearing 2,000MB of standby memory.

Incorrect. With this setting standby memory will be cleared when exceeding the specified amount (2GB in this case). I only repeat what's in the README.md.

> If my interpretation is correct then, I still hate it.

Still no valid reason.

> Any way, in those earlier days because my RAM was being maxed out by this "feature" it would sometimes freeze up my computer or make it "stumble" a bit.

Use the app for this purpose only.

> That being said the renewed conversation reminded me of some scenarios where one minute is not a sufficiently short enough span of time to execute clearing the standby memory.

Clearing every minute would only be useful in rare cases where standby memory would take all available memory every minute. But than we are talking about maybe 100 MB or so. In such case the problem is that there is not enough physical RAM to support your workflow, regardless of Windows storing standby data, useless or not. And so it would only beat the purpose. 

> I don't get to play games much though when I do I obviously have to download them. I've noticed that anything downloaded goes straight in to standby automatically and that very quickly grows the standby waste of memory.

Then set a minimum of available memory, free of such waste.

> For those who have a burning passion for wasting RAM by standby: No threshold: always clear the entire standby memory regardless of how much space it may using.

I do not share such a philosophy as it has no factual basis in terms of performance, in my opinion.
 
> I'm not sure about the others but that definition for no threshold makes the most sense.

There is still the option.

> I've got an AMD 3800 with 32GB of RAM and it's been years since clearing standby memory hurt performance even for the briefest of moments as far as I can recall.

As far as I can tell this app may not be benificial to you then, unless you're running many large programs at the same time.

**Comment by jabcreations** [comment] 2025-01-07 11:17
>Still no valid reason.

Validity is like beauty, it's in the eye of the beholder. It needs to make sense to the person reading the documentation. It wasn't concise and clear enough to me therefore it was combative and I have a thing about poor communication / wasting time. I'm just trying to help you out. When you communicate clearly, concisely and competently you win people's support.

>I do not share such a philosophy as it has no factual basis in terms of performance, in my opinion.

RAM usage effects energy consumption. So it's even more important on laptops running on batter power.

I don't know if it's late (or early) where you're at though it seems like you've got a bit of a block. Again, I'm only trying to be helpful here.

Why did you make the program in the first place? I'd imagine because Windows was wasting your RAM and causing problems and you were able to create an elegant solution. Whatever your reason, your reason is valid to you.

When you appeal to people you need to appeal to what they consider valid. Yes, what you consider valid is still important, to you. However you need to find common ground and relate how your validity applies in their scenarios.

In other words you don't want one square foot of validity that only statically applies to just you. You want a square mile of dynamic validity that encompasses much more. That is how to convince people, how you sell them on what you're doing to help them. Once you know how to appeal to others who communicate differently about the same validity then you can build outwards to extend beyond your immediate sense of validity. Would you rather have ten people using your software or ten thousand?

I have a program that runs in the background. I very rarely actively watch it. It shows the real time log activity for my database queries. When a highlight filter matches it plays a sound. I hear the sound and I know I screwed up. This is way better than learning I screwed something up three days ago to only fix it now. We're not infinite, cemeteries exist for a very real reason. So I'm not only wrong, I'm very wrong and very often wrong. What is important is that I'm aware of when I'm wrong and that I have the intention of self-correction.

If you want to make your life one worth living you need to abandon the sense of "ego". Your sense of what is valid is your starting point to comprehending others and how you can help them. If you embrace self-correction and just refine refine refine on what you're doing because you comprehend where that mutual validity is at then you'll go far in life. You don't have to be the first, you just have to do what you do better than others. That is why I use ClearStandbyMemoryScheduler, it's just straight up better than other options period. If you keep the earlier attitude of trying to do things better (which certainly ending up bearing fruit!) then you'll have that realization that learning if the detection of patterns. Repeat that pattern and you'll find success. So find the common validity. I'm here willing to help you do that. Trust me, there is a reason why my platform is on it's 35th release. I certainly didn't get it right the first time, no one does.

**Comment by jabcreations** [comment] 2025-01-07 11:19
Oh by the way, a good marketing point would be to test battery life in a before-and-after scenario for laptops. I'm not a laptop enthusiast though anyone who is would likely appreciate whatever the improvement would be that your program can give them. So work with me to refine the clarifications and then it'll make your program that much more valuable to more people. 🙂︀

**Comment by rafcolson** [comment] 2025-01-07 11:39
> So work with me to refine the clarifications and then it'll make your program that much more valuable to more people. 🙂︀

I'm not at all convinced that the info is unclear. So I won't be changing it.

**Comment by rafcolson** [comment] 2025-05-09 00:05
> Would you rather have ten people using your software or ten thousand?

@jabcreations Was reading your post again after considering to make some changes to the program. Still not my main objective to reach people with this software. However I guess you could make the argument that by doing so, there is a higher change more people could benefit from the software.

In any case, I've decided to change the interval unit to seconds. See #9 .

**Comment by jabcreations** [comment] 2025-05-09 00:21
@rafcolson That sounds great! I'll reply over there with a question / idea pair you might like.

**Comment by rafcolson** [comment] 2025-05-09 02:50
> I'll reply over there with a question / idea pair you might like.

If I didn't understand the question, feel free to elaborate in a new issue. Bye for now.
